[package]
name = "janus-p2p"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
janus-plugin = "0.7.1"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
